### ISSUE TITLE
Create Wireframes

### ISSUE THREAD

**Issue by cdelorme** [FOSSRIT/Open-Video-chat#3]
For a consistent cross platform UI, using the Sugar original create an outline of the OVC GUI.

**Comment by KevinMGranger** [comment]
Have a wireframe app in mind yet?

**Comment by cdelorme** [comment]
Not yet, debating between Dia and Omnigraffle, worst case hand-drawn (still the most flexible).  Did you have some suggestions?

**Comment by cdelorme** [comment]
Created hand-drawn wire frames, all set to move forward with Use Cases.

Depending on tool feasibility I may recreate the wireframes via dia later.
